FROM python:3.7-slim-buster

RUN pip3 install pandas==1.1.3 numpy==1.19.2 pyarrow==2.0.0 scikit-learn==0.22.1 awswrangler==2.3.0
ENV PYTHONUNBUFFERED=TRUE

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y unzip
RUN apt-get install -y curl

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install
RUN rm awscliv2.zip
RUN rm -rf aws
RUN aws --version

ENTRYPOINT ["python3"]