name: spark-study2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.4
  - notebook
  - pip


  - pip:
    - awswrangler==2.11.0
    - beautifulsoup4==4.9.3
    - boto3==1.18.36
    - botocore==1.21.36
    - matplotlib==3.4.2
    - wordcloud==1.8.1
    - numpy==1.21.2
    - pandas==1.2.4
    - pyspark==3.1.2
    - pyspark-stubs==3.0.0.post2
    - requests==2.25.1
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - seaborn==0.11.1
    - slackclient==2.9.3
    - tensorflow==2.6.0
    - mplfinance==0.12.7a17
    - spark-nlp==3.3.2
    - xgboost==1.5.0